// Ícones do sistema (lucide-react, só os usados entram no pacote). Use SEMPRE por estes
// nomes semânticos, nunca setas de texto (→ ← ↑ ↓ ×): assim o mesmo gesto tem o mesmo ícone
// em todas as telas.
export {
  ArrowLeft as IconBack,
  ChevronRight as IconOpen,
  ChevronUp as IconMoveUp,
  ChevronDown as IconMoveDown,
  X as IconRemove,
  Plus as IconAdd,
  Pencil as IconEdit,
  Trash2 as IconDelete,
  Eye as IconView,
  RotateCcw as IconReuse,
  CalendarClock as IconReschedule,
  Play as IconStart,
  Pause as IconPause,
  Square as IconStop,
  Search as IconSearch,
  LayoutDashboard as IconHome,
  Megaphone as IconCampaigns,
  History as IconHistory,
  MessageCircle as IconWhatsApp,
  ShieldCheck as IconAdmin,
  UserRound as IconAccount,
  LogOut as IconLogout,
  Users as IconGroups,
  Clock as IconClock,
  Send as IconSent,
  CheckCheck as IconDelivered,
  Eye as IconReads,
  CircleAlert as IconAlert,
  Image as IconImage,
  Video as IconVideo,
  Upload as IconUpload,
  RefreshCw as IconRefresh,
  KeyRound as IconPassword,
  Ban as IconDisable,
  CircleCheck as IconEnable,
  Loader2 as IconLoading,
  Inbox as IconEmpty,
  Timer as IconQueue,
  Radio as IconReach,
  ChevronDown as IconChevron,
  Check as IconCheck,
  AtSign as IconMention,
} from 'lucide-react';
